### ISSUE TITLE
Согласовать систему понятий

### ISSUE THREAD

**Issue by ShunkevichDV** [savushkin-r-d/s88-ostis#3]

**Comment by fabishevskaya** [comment]
будет ли корректен перевод слов "ячейка" - "осередок" и "оборудование" - "устаткуванне"?
так же как правильнее перевести словосочетания "управляющий рецепт" и "установочный рецепт"?

**Comment by idzm** [comment]
@fabishevskaya - а у вас есть ссылка на украинский вариант стандарта?

**Comment by idzm** [comment]
[Здесь](https://tk185.appau.org.ua/61512/ukr/) находится перевод на украинский язык.

**Comment by fabishevskaya** [comment]
на что опираться, если нет конкретного перевода?
то есть, например, мне нужен перевод "recipe operation", но в глосарии есть только "recipe operation procedure"
можно считать их эквивалентными?

**Comment by fabishevskaya** [comment]
так же вопрос по поводу html-страниц
в глоссарии в переводе присутствуют "примітка", надо ли ее переносить в html?

**Comment by fabishevskaya** [comment]
@idzm 
1. мною не было обнаружено хоть какое упоминание термина "equipment relation", ни в книге, ни в глоссарии
2. относительное понятие "contains*" - перевода нет
3. относительное понятие "process element link*" - нет перевода
4. "recipe procedural element" перевода как такового нет, есть перевод терминов "define general recipe procedural elements" и "define master recipe procedural elements"
5. перевод "process element" отсутствует
6. "equipment procedural element" - аналогичная ситуация, как в пункте выше - есть "procedural elemen" и "equipment procedure"

**Comment by idzm** [comment]
@fabishevskaya - самый простой вариант, если только остались эти понятия, то можно их убрать из базы знаний.

**Comment by idzm** [comment]
Также остается вопрос - как понятия собрать вместе? Сразу перевод в базу знаний помещаем или через промежуточный документ?

**Comment by idzm** [comment]
> 
> 
> @idzm
> 
>     1. мною не было обнаружено хоть какое упоминание термина "equipment relation", ни в книге, ни в глоссарии
> 
>     2. относительное понятие "contains*" - перевода нет
> 
>     3. относительное понятие "process element link*" - нет перевода
> 
>     4. "recipe procedural element" перевода как такового нет, есть перевод терминов "define general recipe procedural elements" и "define master recipe procedural elements"
> 
>     5. перевод "process element" отсутствует
> 
>     6. "equipment procedural element" - аналогичная ситуация, как в пункте выше - есть "procedural elemen" и "equipment procedure"

@pupenasan - нужна ваша помощь.

**Comment by idzm** [comment]
Есть еще [глоссарий](https://www.dropbox.com/s/wyf0cigwv8ce8a2/%D0%B3%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9.xlsx?dl=0). Можно его использовать.

**Comment by idzm** [comment]
В *excel*-формате неудобно хранить (сложно просматривать онлайн в браузере, неудобно с историей изменений работать). Может в табличном виде в *.md формате хранить? Было бы не плохо иметь механизм экспорта-импорта понятий из БЗ (через таблицу в *.md формате).

**Comment by fabishevskaya** [comment]
> Есть еще [глоссарий](https://www.dropbox.com/s/wyf0cigwv8ce8a2/%D0%B3%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9.xlsx?dl=0). Можно его использовать.

смотрела
там этого нет
зато есть пару опечаток. надо ли их исправлять?

**Comment by fabishevskaya** [comment]
остался вопрос по поводу примечаний в переводе
делать их, если в русской версии их нет?

**Comment by idzm** [comment]
> 
> 
> > Есть еще [глоссарий](https://www.dropbox.com/s/wyf0cigwv8ce8a2/%D0%B3%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9.xlsx?dl=0). Можно его использовать.
> 
> смотрела
> там этого нет
> зато есть пару опечаток. надо ли их исправлять?

Да, исправляем.

**Comment by idzm** [comment]
> 
> 
> остался вопрос по поводу примечаний в переводе
> делать их, если в русской версии их нет?

Да, делаем. Потом после обсуждения определимся, оставлять их или нет.

**Comment by fabishevskaya** [comment]
подскажите, пожалуйста, где можно найти переведенные стандарты для PFC?
ни в одной файле я его не нашла

**Comment by idzm** [comment]
А какие именно термины из PFC-области вызывают вопросы?

**Comment by pupenasan** [comment]
> 
> 
> @idzm
> 
>     1. мною не было обнаружено хоть какое упоминание термина "equipment relation", ни в книге, ни в глоссарии
> 
>     2. относительное понятие "contains*" - перевода нет
> 
>     3. относительное понятие "process element link*" - нет перевода
> 
>     4. "recipe procedural element" перевода как такового нет, есть перевод терминов "define general recipe procedural elements" и "define master recipe procedural elements"
> 
>     5. перевод "process element" отсутствует
> 
>     6. "equipment procedural element" - аналогичная ситуация, как в пункте выше - есть "procedural elemen" и "equipment procedure" 
@fabishevskaya уточните откуда берутся термины (какой стандарт) и в каких местах ищется их перевод?

**Comment by idzm** [comment]
@fabishevskaya - термины берём из текущего состояния БЗ. Перевод берем из [глоссария](https://www.dropbox.com/s/wyf0cigwv8ce8a2/%D0%B3%D0%BB%D0%BE%D1%81%D0%B0%D1%80%D1%96%D0%B9.xlsx?dl=0), если его там нет - перевод предлагаем свой.

**Comment by fabishevskaya** [comment]
> А какие именно термины из PFC-области вызывают вопросы?

как называется стандарт, в котором они переведены?
возможно, я просто не увидела

**Comment by fabishevskaya** [comment]
при объяснении понятия присутствует ссылка на "технічне устаткування" - "hardware", но самого понятия нет
что с этим делать?

**Comment by pupenasan** [comment]
> как называется стандарт, в котором они переведены?
> возможно, я просто не увидела
для PFC нет переведенного стандарта на украинский. Это часть 2-я. Есть ГОСТ Р МЭК 61512-2-2016, может там есть адекватные переводы. Их я откровенно не смотрел, по этому степень адекватности оценить трудно.

**Comment by pupenasan** [comment]
> 
> 
> @idzm
> при объяснении понятия присутствует ссылка на "технічне устаткування" - "hardware", но самого понятия нет
> что с этим делать?

Понятие "тех**нолог**ічне   устатковання" это "технологическое оборудование" или просто "оборудование". Англоязычный термин - Equipment. Его трактовки в стандартах нет, но есть аналог в других стандартах. У нас это  ДСТУ 2391-2010:
50 | Equipment | технологічне   устатковання,   устатковання |   Засоби   технологічної   оснащеності,   в яких   розміщують   матеріали   або   заготованки  засоби   дії на них а   також   технологічну   оснастку   дпя виконування   певної   частини   технологічного   nроцecу.   Примітка.   Наприклад,   ливарні машини,   преси,   верстати,   печі,   гальванічні   ванни,   випробувальні   стенди, тощо.   (ДСТУ 2391-2010)

**Comment by fabishevskaya** [comment]
> > как называется стандарт, в котором они переведены?
> > возможно, я просто не увидела
> 
> для PFC нет переведенного стандарта на украинский. Это часть 2-я. Есть ГОСТ Р МЭК 61512-2-2016, может там есть адекватные переводы. Их я откровенно не смотрел, по этому степень адекватности оценить трудно.

хорошо, а что тогда делать с этим? откуда брать информацию?

**Comment by fabishevskaya** [comment]
в нескольких html страничках присутствует понятие "производственная деятельность", которое отмечено как "manufacturing_operation", но в стандарте есть "Технологічна дія" - "process action"
менять ли "manufacturing_operation" на "process action"?

**Comment by fabishevskaya** [comment]
@idzm 
для работы с PFC-областью нужна вторая часть стандарта 61512. 
есть ли она в доступе?

**Comment by idzm** [comment]
@fabishevskaya - предлагаю текущие правки в виде черновика запроса на внесение изменений (draft pull request) оформить, а то вы работаете, работаете, а потом накатите очень большой объем изменений.

**Comment by idzm** [comment]
> @idzm
> для работы с PFC-областью нужна вторая часть стандарта 61512.
> есть ли она в доступе?
Попробуйте поискать в Интернете, если не найдёте, будем думать.

**Comment by idzm** [comment]
> 
> 
> в нескольких html страничках присутствует понятие "производственная деятельность", которое отмечено как "manufacturing_operation", но в стандарте есть "Технологічна дія" - "process action"
> менять ли "manufacturing_operation" на "process action"?

Тут надо смотреть контекст. Я предлагаю пока это не менять.

**Comment by fabishevskaya** [comment]
> > @idzm
> > для работы с PFC-областью нужна вторая часть стандарта 61512.
> > есть ли она в доступе?
> 
> @fabishevskaya - попробуйте поискать в Интернете, если не найдёте, будем думать.

к сожалению, найти в интернете вторую часть стандарта я не смогла
она есть на русском, а мне нужно на другом языке

**Comment by idzm** [comment]
@fabishevskaya - нужно открыть в настройках свой почтовый адрес, я более подробное описание как сделать *draft pull request* скину на почту.

**Comment by fabishevskaya** [comment]
> @fabishevskaya - нужно открыть в настройках свой почтовый адрес, я более подробное описание как сделать _draft pull request_ скину на почту.

сделано

**Comment by idzm** [comment]
Работа реализована здесь #4.
