### ISSUE TITLE
Добавить общее описание репозитория

### ISSUE THREAD

**Issue by pupenasan** [savushkin-r-d/s88-ostis#5]
Счиатаю, что стоит описать предназначение репозитория в README, если мы хотим чтобы проект развивался. 
- [ ] о проекте
- [ ] общее описание разделов
- [ ] видение развития проекта с вовлечением коллег  
- [ ] об OSTIS (на сколько мне известно нет репозиториев, где бы это было написано)

**Comment by pupenasan** [comment]
@idzm стоит указать открытые источники, где это используется. Если есть статьи, может тоже выложить их тут?

**Comment by pupenasan** [comment]
@ShunkevichDV то что ты мне выслал по OSTIS можно обрабатывать и выкладывать сюда в репозиторий?

**Comment by NikitaZotov** [comment]
> Счиатаю, что стоит описать предназначение репозитория в README, если мы хотим чтобы проект развивался.
> 
>     * [ ]  о проекте
> 
>     * [ ]  общее описание разделов
> 
>     * [ ]  видение развития проекта с вовлечением коллег
> 
>     * [ ]  об OSTIS (на сколько мне известно нет репозиториев, где бы это было написано)

Добрый вечер. Это весь список описаний, которые вы бы хотели видеть?

**Comment by pupenasan** [comment]
> Добрый вечер. Это весь список описаний, которые вы бы хотели видеть?

пока да :)

**Comment by ShunkevichDV** [comment]
описание OSTIS лучше тут не приводить, а дать ссылку на один из репозиториев на ostis-dev
например на ims.ostis.kb
