### ISSUE TITLE
Общее

### ISSUE THREAD

**Issue by pupenasan** [savushkin-r-d/s88-ostis#7]
Создал чтобы тут обсуждать потенциальные общие вопросы.

**Comment by pupenasan** [comment]
@ShunkevichDV @idzm Может успеем податься сюда [Конкурс совместных белорусско-украинских научно-технических проектов на 2021 – 2022 годы](http://gknt.gov.by/deyatelnost/konkurs-sovmestnykh-belorussko-ukrainskikh-nauchno-tekhnicheskikh-proektov-na-2021-2022-gody.php?clear_cache=Y)

**Comment by idzm** [comment]
Можно попробовать - с нашей стороны как участник больше @ShunkevichDV будет. Моя роль ближе к заказчику. Тут ещё интересен опыт @ShunkevichDV участия в подобных проектах.

**Comment by ShunkevichDV** [comment]
@pupenasan, я настоятельно рекомендую не обсуждать общие вопросы на гитхабе, тем более в Issues, есть мессенджеры для этого, можно Slack (там есть чат с нами тремя), можно любые другие, я в любом готов. Предлагаю определиться с местом общения и продолжить там

**Comment by idzm** [comment]
Да, специфические вопросы обсуждаем в мессенджерах, если есть что-то похожее на **issue**, то тогда можно предварительно обсудить это здесь - https://github.com/savushkin-r-d/s88-ostis/discussions.
